import type { Venue, VenueRules } from "@/lib/types/spaces";

/** All seed venues were "created" at the same fixed moment — they're not real submissions. */
const SEED_CREATED_AT = "2026-01-01T00:00:00.000Z";

function rules(overrides: Partial<VenueRules>): VenueRules {
  return {
    alcoholAllowed: false,
    amplifiedMusicAllowed: false,
    outsideCateringAllowed: false,
    ticketedEventsAllowed: false,
    lateNightEventsAllowed: false,
    coiRequired: false,
    securityDepositRequired: false,
    ...overrides,
  };
}

/**
 * Entirely fictional listings for the Discover Spaces prototype. Names,
 * descriptions, and coordinates (neighborhood-level, not street addresses)
 * are invented — none represent real operating businesses. "The Ironworks"
 * intentionally matches the venue name referenced by the fictional
 * testimonial in RecapCarousel.tsx.
 */
const SEED_VENUES: Omit<Venue, "ownerId" | "createdAt" | "exactAddress">[] = [
  {
    id: "v-neon-foundry",
    slug: "neon-foundry",
    name: "Neon Foundry",
    tagline: "A raw industrial shell built for big nights.",
    description:
      "A 6,000 sq ft converted metal shop in SoMa with soaring ceilings, exposed steel trusses, and a fully programmable colored-lighting rig. Neon Foundry is built for parties, brand takeovers, and live sets that need room to breathe.",
    neighborhood: "SoMa",
    city: "San Francisco",
    coordinates: { lat: 37.7785, lng: -122.4056 },
    spaceType: "warehouse",
    eventTypes: ["party", "brand_activation", "performance", "corporate"],
    maxCapacity: 400,
    seatedCapacity: 120,
    minBookingHours: 4,
    minHourlyRate: 150,
    maxHourlyRate: 300,
    images: ["1", "2", "3", "4", "5"],
    visualAccent: ["#ff2fb0", "#2fd3ff"],
    icon: "🎛️",
    amenities: [
      "dj_speakers",
      "dj_controller",
      "sound_system",
      "colored_lighting",
      "bar",
      "security_available",
      "ada_accessible",
      "wifi",
      "parking",
    ],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      outsideCateringAllowed: true,
      ticketedEventsAllowed: true,
      lateNightEventsAllowed: true,
      coiRequired: true,
      securityDepositRequired: true,
    }),
    availabilityExamples: ["Weeknights after 7pm", "Weekends, all day"],
    badge: "nightlife",
  },
  {
    id: "v-lantern-house",
    slug: "lantern-house",
    name: "Lantern House",
    tagline: "A red-lacquered cocktail den above Chinatown.",
    description:
      "An intimate second-floor lounge with hand-painted lantern fixtures, a full bar, and a private back room. Lantern House suits dinners, toasts, and after-work gatherings that want atmosphere without the warehouse scale.",
    neighborhood: "Chinatown",
    city: "San Francisco",
    coordinates: { lat: 37.7941, lng: -122.4078 },
    spaceType: "lounge",
    eventTypes: ["dinner", "party", "corporate", "community_gathering"],
    maxCapacity: 90,
    seatedCapacity: 50,
    minBookingHours: 3,
    minHourlyRate: 120,
    maxHourlyRate: 220,
    images: ["1", "2", "3", "4"],
    visualAccent: ["#c0142f", "#e0a63a"],
    icon: "🏮",
    amenities: [
      "bar",
      "bartenders_available",
      "sound_system",
      "colored_lighting",
      "wifi",
      "bathrooms",
      "coat_check",
    ],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      ticketedEventsAllowed: true,
      lateNightEventsAllowed: true,
      coiRequired: true,
    }),
    availabilityExamples: ["Tuesday–Sunday evenings"],
    badge: "popular",
  },
  {
    id: "v-the-afterlight",
    slug: "the-afterlight",
    name: "The Afterlight",
    tagline: "An underground room built around sound.",
    description:
      "A below-grade listening room with a custom sound system and low, moody lighting. The Afterlight hosts DJ sets, small live shows, and late-night gatherings for people who take their sound seriously.",
    neighborhood: "Tenderloin",
    city: "San Francisco",
    coordinates: { lat: 37.7838, lng: -122.4142 },
    spaceType: "lounge",
    eventTypes: ["performance", "party", "community_gathering"],
    maxCapacity: 120,
    seatedCapacity: 60,
    minBookingHours: 3,
    minHourlyRate: 100,
    maxHourlyRate: 180,
    images: ["1", "2", "3"],
    visualAccent: ["#2b1055", "#7597de"],
    icon: "🎧",
    amenities: [
      "sound_system",
      "dj_controller",
      "microphones",
      "colored_lighting",
      "bar",
      "bathrooms",
    ],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      ticketedEventsAllowed: true,
      lateNightEventsAllowed: true,
    }),
    availabilityExamples: ["Thursday–Saturday, 8pm–2am"],
    badge: "nightlife",
  },
  {
    id: "v-harbor-room",
    slug: "harbor-room",
    name: "Harbor Room",
    tagline: "A daylit loft facing the water.",
    description:
      "A converted dockside loft with floor-to-ceiling windows facing the bay, an open kitchen, and a private patio. Harbor Room works well for dinners, offsites, and daytime celebrations that want natural light.",
    neighborhood: "Dogpatch",
    city: "San Francisco",
    coordinates: { lat: 37.7583, lng: -122.3888 },
    spaceType: "loft",
    eventTypes: ["dinner", "corporate", "brand_activation", "wedding"],
    maxCapacity: 150,
    seatedCapacity: 80,
    minBookingHours: 4,
    minHourlyRate: 175,
    maxHourlyRate: 350,
    images: ["1", "2", "3", "4"],
    visualAccent: ["#1c3f5f", "#8fb8d9"],
    icon: "🌉",
    amenities: [
      "kitchen",
      "wifi",
      "tables_chairs",
      "ada_accessible",
      "parking",
      "outdoor_area",
      "television",
    ],
    rules: rules({
      alcoholAllowed: true,
      outsideCateringAllowed: true,
      coiRequired: true,
      securityDepositRequired: true,
    }),
    availabilityExamples: ["Weekdays, daytime", "Saturday, by request"],
  },
  {
    id: "v-concrete-garden",
    slug: "concrete-garden",
    name: "Concrete Garden",
    tagline: "A walled courtyard with room to gather outside.",
    description:
      "A hidden garden courtyard behind a converted storefront, strung with lights and framed by raised planters. Concrete Garden is built for daytime and early-evening gatherings that want fresh air.",
    neighborhood: "Bernal Heights",
    city: "San Francisco",
    coordinates: { lat: 37.744, lng: -122.4159 },
    spaceType: "outdoor",
    eventTypes: ["party", "wedding", "community_gathering", "popup"],
    maxCapacity: 100,
    seatedCapacity: 60,
    minBookingHours: 3,
    minHourlyRate: 90,
    maxHourlyRate: 160,
    images: ["1", "2", "3"],
    visualAccent: ["#3c5a3e", "#c9d9a8"],
    icon: "🌿",
    amenities: [
      "outdoor_area",
      "colored_lighting",
      "tables_chairs",
      "bathrooms",
      "animal_friendly",
      "wifi",
    ],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      outsideCateringAllowed: true,
      ticketedEventsAllowed: true,
      coiRequired: true,
    }),
    availabilityExamples: ["Daytime and early evening, year-round"],
  },
  {
    id: "v-skyline-atrium",
    slug: "skyline-atrium",
    name: "Skyline Atrium",
    tagline: "An open-air rooftop above the city.",
    description:
      "A rooftop deck with unobstructed downtown skyline views, a full bar setup, and a covered lounge area for overflow. Skyline Atrium is a favorite for launch parties and golden-hour receptions.",
    neighborhood: "SoMa",
    city: "San Francisco",
    coordinates: { lat: 37.78, lng: -122.403 },
    spaceType: "rooftop",
    eventTypes: ["party", "corporate", "brand_activation", "photo_video_shoot"],
    maxCapacity: 180,
    seatedCapacity: 70,
    minBookingHours: 4,
    minHourlyRate: 200,
    maxHourlyRate: 400,
    images: ["1", "2", "3", "4", "5"],
    visualAccent: ["#ff7a45", "#2b3a67"],
    icon: "🌆",
    amenities: [
      "bar",
      "sound_system",
      "colored_lighting",
      "outdoor_area",
      "wifi",
      "ada_accessible",
      "photo_booth_area",
    ],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      outsideCateringAllowed: true,
      ticketedEventsAllowed: true,
      lateNightEventsAllowed: true,
      coiRequired: true,
      securityDepositRequired: true,
    }),
    availabilityExamples: ["Weekday evenings", "Weekends, all day"],
    badge: "popular",
  },
  {
    id: "v-redline-loft",
    slug: "redline-loft",
    name: "Redline Loft",
    tagline: "A stripped-back loft for shoots and small workshops.",
    description:
      "An exposed-brick loft with clean white walls, adjustable daylight blackout curtains, and a small kitchenette. Redline Loft is priced for shorter bookings — shoots, workshops, and small pop-ups.",
    neighborhood: "Hayes Valley",
    city: "San Francisco",
    coordinates: { lat: 37.7759, lng: -122.4245 },
    spaceType: "loft",
    eventTypes: ["photo_video_shoot", "workshop", "popup", "brand_activation"],
    maxCapacity: 70,
    seatedCapacity: 40,
    minBookingHours: 2,
    minHourlyRate: 85,
    maxHourlyRate: 150,
    images: ["1", "2", "3"],
    visualAccent: ["#7a4a2f", "#e8c9a0"],
    icon: "🧱",
    amenities: ["wifi", "television", "projector", "tables_chairs", "bathrooms", "kitchen"],
    rules: rules({ outsideCateringAllowed: true }),
    availabilityExamples: ["Weekdays, daytime"],
    badge: "new",
  },
  {
    id: "v-glasshouse-social",
    slug: "glasshouse-social",
    name: "Glasshouse Social",
    tagline: "A minimal studio built for clean shots.",
    description:
      "A white-cyc photography studio with adjustable soft lighting and a small client lounge. Glasshouse Social is built for shoots, product launches, and small brand workshops that need a blank canvas.",
    neighborhood: "Potrero Hill",
    city: "San Francisco",
    coordinates: { lat: 37.7677, lng: -122.4001 },
    spaceType: "studio",
    eventTypes: ["photo_video_shoot", "workshop", "brand_activation"],
    maxCapacity: 40,
    seatedCapacity: 25,
    minBookingHours: 2,
    minHourlyRate: 75,
    maxHourlyRate: 140,
    images: ["1", "2", "3"],
    visualAccent: ["#e9e6df", "#b9b2a3"],
    icon: "📷",
    amenities: ["wifi", "television", "projector", "tables_chairs", "bathrooms", "ada_accessible"],
    rules: rules({ outsideCateringAllowed: true }),
    availabilityExamples: ["Daily, 8am–8pm"],
    badge: "new",
  },
  {
    id: "v-sanctuary-hall",
    slug: "sanctuary-hall",
    name: "Sanctuary Hall",
    tagline: "A converted chapel with soaring ceilings.",
    description:
      "A deconsecrated chapel with original stained glass, exposed timber trusses, and a wide central hall. Sanctuary Hall hosts ceremonies, performances, and gatherings that call for a little grandeur.",
    neighborhood: "Mission District",
    city: "San Francisco",
    coordinates: { lat: 37.7599, lng: -122.4148 },
    spaceType: "gallery",
    eventTypes: ["wedding", "performance", "corporate", "community_gathering"],
    maxCapacity: 250,
    seatedCapacity: 150,
    minBookingHours: 4,
    minHourlyRate: 200,
    maxHourlyRate: 380,
    images: ["1", "2", "3", "4"],
    visualAccent: ["#4a3728", "#d9c6a5"],
    icon: "⛪",
    amenities: ["sound_system", "microphones", "tables_chairs", "bathrooms", "ada_accessible", "wifi", "parking"],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      outsideCateringAllowed: true,
      ticketedEventsAllowed: true,
      coiRequired: true,
      securityDepositRequired: true,
    }),
    availabilityExamples: ["Weekends, daytime and evening"],
  },
  {
    id: "v-the-green-room",
    slug: "the-green-room",
    name: "The Green Room",
    tagline: "A private dining room for small gatherings.",
    description:
      "A wood-paneled private dining room with its own entrance, a dedicated small kitchen, and seating for up to 24. The Green Room is built for dinners, small offsites, and toasts.",
    neighborhood: "Financial District",
    city: "San Francisco",
    coordinates: { lat: 37.7946, lng: -122.3999 },
    spaceType: "private_dining",
    eventTypes: ["dinner", "corporate", "wedding"],
    maxCapacity: 30,
    seatedCapacity: 24,
    minBookingHours: 2,
    minHourlyRate: 110,
    maxHourlyRate: 200,
    images: ["1", "2", "3"],
    visualAccent: ["#2e3b2e", "#c7a15a"],
    icon: "🍽️",
    amenities: ["kitchen", "bar", "wifi", "television", "tables_chairs", "bathrooms"],
    rules: rules({ alcoholAllowed: true }),
    availabilityExamples: ["Weeknights, 6pm–11pm"],
  },
  {
    id: "v-last-call",
    slug: "last-call",
    name: "Last Call",
    tagline: "A full restaurant, yours after close.",
    description:
      "A neighborhood Italian restaurant that opens its dining room and full bar for private events after closing. Last Call comes with a working kitchen, house bar staff, and a jukebox nobody can agree on.",
    neighborhood: "North Beach",
    city: "San Francisco",
    coordinates: { lat: 37.806, lng: -122.4103 },
    spaceType: "restaurant",
    eventTypes: ["party", "dinner", "corporate", "popup"],
    maxCapacity: 80,
    seatedCapacity: 60,
    minBookingHours: 3,
    minHourlyRate: 140,
    maxHourlyRate: 260,
    images: ["1", "2", "3", "4"],
    visualAccent: ["#5c1a34", "#e0a63a"],
    icon: "🍸",
    amenities: ["kitchen", "bar", "bartenders_available", "sound_system", "wifi", "tables_chairs", "bathrooms"],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      ticketedEventsAllowed: true,
      lateNightEventsAllowed: true,
      coiRequired: true,
    }),
    availabilityExamples: ["Sunday–Thursday, after 10pm"],
  },
  {
    id: "v-static-theatre",
    slug: "static-theatre",
    name: "Static Theatre",
    tagline: "A black-box room built for a mic and a crowd.",
    description:
      "A 100-seat black-box performance room with a small stage, house PA, and a bar in the lobby. Static Theatre hosts comedy nights, small performances, and community showcases.",
    neighborhood: "Tenderloin",
    city: "San Francisco",
    coordinates: { lat: 37.786, lng: -122.416 },
    spaceType: "lounge",
    eventTypes: ["performance", "party", "community_gathering"],
    maxCapacity: 100,
    seatedCapacity: 80,
    minBookingHours: 3,
    minHourlyRate: 95,
    maxHourlyRate: 170,
    images: ["1", "2", "3"],
    visualAccent: ["#1a1a2e", "#e94560"],
    icon: "🎤",
    amenities: ["sound_system", "microphones", "colored_lighting", "bar", "bathrooms", "ada_accessible"],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      ticketedEventsAllowed: true,
      lateNightEventsAllowed: true,
    }),
    availabilityExamples: ["Wednesday–Sunday evenings"],
  },
  {
    id: "v-ember-study",
    slug: "ember-study",
    name: "Ember Study",
    tagline: "A hands-on studio for making things together.",
    description:
      "A light-filled workshop studio with long communal tables, a small kitchenette, and storage for materials. Ember Study is built for classes, craft nights, and small maker pop-ups.",
    neighborhood: "Japantown",
    city: "San Francisco",
    coordinates: { lat: 37.7854, lng: -122.4297 },
    spaceType: "studio",
    eventTypes: ["workshop", "community_gathering", "popup"],
    maxCapacity: 35,
    seatedCapacity: 30,
    minBookingHours: 2,
    minHourlyRate: 60,
    maxHourlyRate: 110,
    images: ["1", "2", "3"],
    visualAccent: ["#8a5a3c", "#f2d9b8"],
    icon: "🕯️",
    amenities: ["wifi", "kitchen", "tables_chairs", "bathrooms", "ada_accessible", "projector"],
    rules: rules({ outsideCateringAllowed: true }),
    availabilityExamples: ["Weekday evenings", "Saturday mornings"],
    badge: "new",
  },
  {
    id: "v-the-ironworks",
    slug: "the-ironworks",
    name: "The Ironworks",
    tagline: "A weeknight-quiet warehouse, wide open on weekends.",
    description:
      "A former metalworking shop with 20-foot ceilings, a full DJ rig, and a fenced loading yard for load-in. The Ironworks sits empty most weeknights and comes alive for parties and shows on the weekend.",
    neighborhood: "Dogpatch",
    city: "San Francisco",
    coordinates: { lat: 37.7583, lng: -122.39 },
    spaceType: "warehouse",
    eventTypes: ["party", "brand_activation", "corporate", "performance"],
    maxCapacity: 350,
    seatedCapacity: 100,
    minBookingHours: 4,
    minHourlyRate: 160,
    maxHourlyRate: 320,
    images: ["1", "2", "3", "4"],
    visualAccent: ["#374151", "#9ca3af"],
    icon: "⚙️",
    amenities: ["dj_speakers", "sound_system", "colored_lighting", "bar", "security_available", "parking", "ada_accessible"],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      outsideCateringAllowed: true,
      ticketedEventsAllowed: true,
      lateNightEventsAllowed: true,
      coiRequired: true,
      securityDepositRequired: true,
    }),
    availabilityExamples: ["Weeknights, by request", "Weekends, all day"],
    badge: "popular",
  },
  {
    id: "v-marina-vista",
    slug: "marina-vista",
    name: "Marina Vista",
    tagline: "An open-air deck looking out over the marina.",
    description:
      "A private rooftop deck with sweeping views of the marina and the bridge beyond. Marina Vista is built for receptions, brand moments, and golden-hour photography.",
    neighborhood: "Marina",
    city: "San Francisco",
    coordinates: { lat: 37.803, lng: -122.438 },
    spaceType: "rooftop",
    eventTypes: ["wedding", "corporate", "party", "photo_video_shoot"],
    maxCapacity: 120,
    seatedCapacity: 70,
    minBookingHours: 3,
    minHourlyRate: 180,
    maxHourlyRate: 340,
    images: ["1", "2", "3", "4"],
    visualAccent: ["#204060", "#a8d0e6"],
    icon: "⛵",
    amenities: ["outdoor_area", "bar", "wifi", "ada_accessible", "photo_booth_area", "tables_chairs"],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      outsideCateringAllowed: true,
      ticketedEventsAllowed: true,
      coiRequired: true,
      securityDepositRequired: true,
    }),
    availabilityExamples: ["Weekends, daytime"],
  },
  {
    id: "v-gallery-nine",
    slug: "gallery-nine",
    name: "Gallery Nine",
    tagline: "A white-walled gallery for shows and launches.",
    description:
      "A street-level art gallery with rotating exhibitions, movable wall panels, and a small projection setup. Gallery Nine hosts openings, brand activations, and pop-up shows.",
    neighborhood: "Mission District",
    city: "San Francisco",
    coordinates: { lat: 37.762, lng: -122.413 },
    spaceType: "gallery",
    eventTypes: ["brand_activation", "popup", "performance", "community_gathering", "corporate"],
    maxCapacity: 130,
    seatedCapacity: 60,
    minBookingHours: 3,
    minHourlyRate: 100,
    maxHourlyRate: 200,
    images: ["1", "2", "3"],
    visualAccent: ["#111111", "#e63946"],
    icon: "🖼️",
    amenities: ["wifi", "projector", "television", "tables_chairs", "bathrooms", "ada_accessible", "photo_booth_area"],
    rules: rules({
      alcoholAllowed: true,
      amplifiedMusicAllowed: true,
      outsideCateringAllowed: true,
      ticketedEventsAllowed: true,
      coiRequired: true,
    }),
    availabilityExamples: ["Tuesday–Sunday"],
    badge: "new",
  },
  {
    id: "v-pop-circuit",
    slug: "pop-circuit",
    name: "Pop Circuit",
    tagline: "A flexible storefront built for a limited run.",
    description:
      "A bright corner storefront with movable fixtures, a roll-up display window, and a small stockroom. Pop Circuit is built for retail pop-ups, product launches, and short brand takeovers.",
    neighborhood: "Hayes Valley",
    city: "San Francisco",
    coordinates: { lat: 37.7745, lng: -122.423 },
    spaceType: "retail",
    eventTypes: ["popup", "brand_activation", "photo_video_shoot"],
    maxCapacity: 60,
    seatedCapacity: 20,
    minBookingHours: 2,
    minHourlyRate: 90,
    maxHourlyRate: 170,
    images: ["1", "2", "3"],
    visualAccent: ["#e0d9c8", "#a37b5c"],
    icon: "🛍️",
    amenities: ["wifi", "television", "tables_chairs", "bathrooms", "ada_accessible", "parking"],
    rules: rules({ outsideCateringAllowed: true }),
    availabilityExamples: ["Daily, by the week"],
    badge: "new",
  },
];

/** Seed venues are "nobody owned" — real ownership starts with user-submitted listings. */
export const VENUES: Venue[] = SEED_VENUES.map((venue) => ({
  ...venue,
  ownerId: null,
  createdAt: SEED_CREATED_AT,
  // Never rendered publicly (see the Venue type) — there's no real address
  // behind these fictional listings to begin with.
  exactAddress: "Address on file",
}));

export function getVenueBySlug(slug: string): Venue | undefined {
  return VENUES.find((venue) => venue.slug === slug);
}
